#!/usr/bin/env ruby

if ARGV[0].nil?
  puts "Usage: cookbook-list-dependecies <cookbook-path> <cookbook name>"
  exit 1
end

@cookbook_path = ARGV[0].to_s
cookbook = ARGV[1].to_s

def get_deps(cookbook, dependencies)
  f = File.open("#{@cookbook_path}/#{cookbook}/metadata.rb", "r").each do |line|
    m =/^(\w*\b)\s*["'](\w*-?\w*\b)["'][,]*/.match(line)
    unless m.nil?
      case m[1]
       when "depends"
        dependencies <<  m[2]
        get_deps(m[2], dependencies)
      end
    end
  end
  f.close
  return dependencies
end

def get_version(cookbook)
  f = File.open("#{@cookbook_path}/#{cookbook}/metadata.rb", "r").each do |line|
    m =/^(\w*\b)\s*["']([0-9]*.[0-9]*.[0-9]*)["'][,]*/.match(line)
    unless m.nil?
      case m[1]
       when "version"
        version = m[2]
        return version
      end
    end
  end
  f.close
end


@dependencies = Array.new
@version = String.new
get_deps(cookbook, @dependencies)

@dependencies.uniq.each do |cookbook|
  version = get_version(cookbook)
  puts "depends '#{cookbook}', '= #{version}'"
end
